/// The common version types
pub mod common;

/// Data generated by the build tooling
#[cfg(not(feature = "generic_data"))]
pub mod generated;

mod protocol_verison;
/// Contains Version types that can not be auto generated.
pub mod versions;

pub use protocol_verison::{JavaProtocolVersion, ProtocolVersion};
