/// The common version types
pub mod common;

/// Data generated by the build tooling
#[cfg(not(feature = "generic_data"))]
pub mod generated;

/// Contains Version types that can not be auto generated.
pub mod versions;
mod protocol_verison;

pub use protocol_verison::{ProtocolVersion, JavaProtocolVersion};